cd /gpfs/milgram/scratch60/turk-browne/elb77/HBN/HBN_BIDS/
datalad get sub-NDARAA948VFH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAB458VK9/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAB977GFB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAC331VEH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAC350BZ0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAC495TJ2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAC853CR6/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARAE877NER/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAF535XK6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAG115LZP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAG340ERT/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAH503YG1/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAH948UF0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAK738BGC/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAL828WXM/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAL897CYV/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARAM357BUA/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARAP049KXJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAP176AD1/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAP457WB5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAP782TVC/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAT358XM9/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAT581NDH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAT680GJA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAT709MMX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAT982JTU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAU530GLJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAV554TP2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAW179AYF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAW216PM7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAX272ZJL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARAX277ATU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARAY665GWN/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARBF042LDM/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARBF176LPM/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARBF183RFB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBF851NH6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBH019KPD/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBH512BHA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBK106KRH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBM433VER/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARBN365EV3/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBN620TT7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBP527JWC/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBP770MUM/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBR740NKV/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARBT607PZL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARBU730PN8/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARBV167RMU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARBX974XDR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARBZ925PRF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCA618DGA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCB305AFY/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCC059WTH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCC340ER5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCD296XU9/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCD687JUZ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCF052AE0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCG159AAP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCG438NML/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCG785NND/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCG808HDJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCH628LKW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCJ433TCG/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCK481KRH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCK647MU6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCL008HLA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCL016NHB/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCM811CV1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCM953HKD/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCP642KML/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCR582GKJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCR594JN0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCR743RHQ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCT420MW1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCT889DMB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCU118LMX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCU621EBN/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCU865PBV/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCV154DB9/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCV440TRV/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCV606ZZ5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCV981XUY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCW611MK5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARCW932EU6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCX021XWF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCX462NVA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARCZ947WU5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDA472JE3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDA516MNY/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDA573XGG/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDA656RBN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDB161LU6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDC814WW2/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDC987BMU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDD073JKZ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDD193HUP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDD854GF8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDE319VD1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDE502TEU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDE681UEX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDE827UF0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDE877RFH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDF374LGN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDG077GPH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDG747ULB/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDH086ZKK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDH214UVC/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDJ204EPU/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARDJ970ELG/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDL377ZT7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDL511UND/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDM156AVJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDN393BJH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDN489EXJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDP786HE6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDR236FWH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDR240WKM/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDR439HY2/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDR591AUC/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDR950CGG/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDT528ZZJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDU482DGK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDU602LPX/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDW178AC6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDW711NYZ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDX173WLD/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARDX196MZP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDX433HXA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDX857DLB/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARDY741VEB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDY776AKH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARDZ425JVB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREC238AY4/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREC486ZPV/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREC648WEL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREC777ADZ/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARED628HMQ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREE015WGU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREF164ZUJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREF848YWD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREF893ZM8/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREG013BLG/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREJ327AH7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREK255DEE/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREK395BM3/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREK686WN1/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDAREL410HHK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREM731BYM/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREM757NBG/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREN151YXN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREN999ERM/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREP505XAD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREU073NFU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDAREW937RMY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREX091KUR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREX589EXG/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREY778CR9/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDAREZ416XDW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFA737TG6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFB384XJ9/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARFB528UVB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFB969EMV/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFD316UD2/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFD552FRH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFD620BUW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFE163HVN/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFF061VUK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFF644ZGD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFG364YMG/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFG713PLR/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFG851ZNZ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFJ179MG0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFJ372JDJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFJ494ZDJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFM211KDJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFM619GTV/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFN214WHQ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFP503KJF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFP841PDJ/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARFR301KKP/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFR445XKP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFT176NJP/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFT698LLU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFT787HJW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFU916UZY/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFV061AR5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARFV685ZT2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFY009MNL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARFY525TL2/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGA921UHR/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGB000CW8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGB040MGR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGB060TAM/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGB441VVD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGC148JBJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGC170UK2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGE536BGD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGF445UFB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGF543PM2/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGG423UMK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGH074MU6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGH592NZ2/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGH842VFY/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGJ395FKP/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGJ653MG2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGK041TPB/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGK449LLK/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGL289TB8/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARGL800LDW/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGM196JMM/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGM439FZD/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGN044FE4/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGN210CK7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGN782BZN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGR893PUA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGT551AFK/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGU461JX2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGU844NZ3/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARGV781AMW/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGV948BFZ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGY559UL3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGY622NG6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARGY639ANB/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARGZ553TMQ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHA387FPM/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHB764VZ2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHB803UT9/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHC083LM6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHC462NGR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHC814ZZL/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHD017XEU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHD276TYX/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHD931FNA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHE772FWW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHF150FDY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHG065YHQ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHG152GZC/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHG260BM9/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHH654ZF9/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHH757RT9/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHH802DBM/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHJ034LDM/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHJ830RXD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHL164JHH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHM611GDR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHN911CNJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHP841RMR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHR372GJ7/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHR753ZKU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHT829KKB/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHW158PPR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHW968ABB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHX934KJ5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHX963YU1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHY676RYH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARHZ500ZNT/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARHZ923PAH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJ257ZU2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJA262HTY/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJA356XHT/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJA788CH7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJA959GNZ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJB233RL7/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJB236XDY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJB501MJL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJC010YYF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJC399UW7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJE686DJL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJF322BN4/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJF517HC8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJG298YVA/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJG738WY6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJG740PM8/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJH367WKY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJH492TVW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJH910CGX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJJ173BRX/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARJJ277JP3/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJK147LNJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJL303FKR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJL861WTP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJM765EZF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJM828PAL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJR280FEJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJR437DJH/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARJR473HXT/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJT064LRE/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJT588ZAX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJT615WM7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJV062AM0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJW072UJ3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJW503GA0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJX121GKP/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJX258XF0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARJZ274PRQ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJZ526HN3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARJZ888UX6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKB290YNY/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKB614KGY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKD064EVC/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKF442GZ5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKF779EK2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKF909WM5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKG697CEW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKG859AGN/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKH168MC1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKH171DG8/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKH944KVE/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKJ546WWQ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKK392ZX2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKL156NJG/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARKL327YDQ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKM497VKX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKM784VA7/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKN477EBH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKN633WZA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKN988BRP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKP893TWU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKT540ZW0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKT714TXR/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKV353MTD/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKV461KGZ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKV807EMJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKW010CT2/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKW383ZPF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKX665ZD3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARKX788PHG/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKZ312XR1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARKZ634RVX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLB162XP2/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLB291FBV/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARLB547HJD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLC770YL9/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLE335PRN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLE554GYT/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLF446MT5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLF480DMW/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLG154ZA3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLK690ZK9/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLL626XFF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLL720BGU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLL790WLF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLL894HC3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLL968KK1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLM196YRG/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLN749FML/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLR030EW6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLR083PKF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLT314TWP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLU939YX4/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARLY483UNZ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLY687YDQ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARLZ701LJ3/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMA273ZL6/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARMA449YB6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMA584EM0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMB216LA6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMC759CX3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMF116AFR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMF444MAY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMF560MUH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMG263JRX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMJ219AKU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMK046ZRK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMK100DJR/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMK825WAX/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMM486AJU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMN043YKC/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMN695VFH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMR039JV5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMR134HUY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMV274TAY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMV319CAT/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMV605LGH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMV718DYL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMW178UDD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMX328VWC/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMX835PGE/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARMY873XG5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMZ477MNH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARMZ687XRR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNB427ARE/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARND085WZK/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARND348HB3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNE758RD6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNF873FCV/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNH147WGN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNH285EWA/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARNJ633HHX/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNK322PHW/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNK740ZVM/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNL587LVL/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNM708YTF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNN142WYB/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNN218UGY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNN624AMU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNN761ZPA/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARNT113YX7/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNT151UN1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNT205ZKP/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNT225UVD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNT541VT2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNX223DY3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNX477HZ4/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNY205RK8/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNY419GR2/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNZ043VH0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARNZ084JVC/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNZ141GNH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARNZ615UEU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPA005VVK/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPC745LTD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPC817XZ5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPE056ACA/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPE752VYE/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPE830YU0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPF362VH8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPF395NV5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPF459CME/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPF682GDC/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPF937BDQ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPH105ZFF/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARPH567WUB/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARPJ502KEH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPJ691NEU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPK522DVQ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPL215MTH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPL479LHN/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPL598MVU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPM105MKA/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPN886HH9/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPU329MDJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPU897CM5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPV009TYX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPV412JEN/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARPW786GC4/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPX219TW0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPY478YM0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARPZ720WKW/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARPZ973RK0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRB359CRR/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRB901DWV/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRB942UWU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRC295CHW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRD943ZWU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRF897HB5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRG199RU4/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRJ989YPA/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRK213WCF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRK545WNM/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRK882CLT/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRL315KV3/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRL379BET/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRP801AX1/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRP818DWL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRR622MYT/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRU290EZV/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRU499DP2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRU729XRU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRU979UBW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRV002MA8/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRV217VTA/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARRV688GUX/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRV837BZQ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRW100AU0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRW141HUT/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRW475MPT/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRW536ZM2/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARRW940BL6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRW951BYF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRX897XV1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARRY280KNW/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARRZ927VC3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTB203DU7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARTC795CR3/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARTE432ZRH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTE553VC1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARTE785ZMJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTF566PYH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTF781TM8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARTG937LDA/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTJ433TB5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARTJ862ENU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARTK834FT9/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTN173MXV/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTN760YH8/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTP022VL6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTR175UDC/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARTU280GKF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARTU777GVV/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTV480WBU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARTW850GHU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTW855BPJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTX575YBU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTX659HAF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARTY225EWV/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUA745NA8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUA832MYV/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUC851WHU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUF540ZJ1/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUG091CY1/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUH536DUK/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUJ292JXV/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUK101YT3/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUL290YKN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUL694GYN/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUM791WPF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUN300FG1/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUP249AMD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUR987CDM/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUT470BM4/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUT891XYJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUU615WPR/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUU991VRE/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUV041YCY/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUV263YB5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUW206XUG/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUW816MP3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUX187JTB/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARUX408KJ1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUX885LMW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARUY730ANT/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARUZ368BT4/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVA930UA3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARVB151GXF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVB587ECK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVB819ENX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARVB897AH1/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARVC195NLH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVC673HFA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVD495YP9/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARVF159VP9/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVG127VW5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVG132NF6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVG641YGK/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARVG808PKQ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARVK922KE5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARVL190JA8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVL697YGK/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARVM287DJK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVN280JTN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVN363NNQ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVP285RXV/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARVU416CR6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVX111CNA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVX547MA0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVY366HWJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARVY378DFK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARVY938WR6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWA102TY7/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWA351ZE2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWA433WYZ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWA513WM2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWC174VE6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWC399JLD/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWC426HEA/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWC427JB2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWD585PRZ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWD911WBU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWE717DEU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWE818UA6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWE898TG8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWF306VWJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWF422UK3/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWF514TW5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWG549LCF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWG798MJG/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWH779MZ2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWJ321WKG/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWJ414WB8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWK104FLX/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWK793VK4/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWL656URE/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARWM527PRT/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWM656UWL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWN709HA2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWP732GD1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWP817CVB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWR247CE1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWR628EFJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWR678HLF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWU018VDB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWV405ZW0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWW005GCU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARWX605LAD/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWY718TY7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARWZ865ZMK/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXB692PXC/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXD345GBN/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARXE193CZ1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXF203DCD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARXF497LYF/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXG035ZVM/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARXG961UAB/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARXH529MTX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARXH597ML1/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARXK986EK6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXL697DA6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXL801JVG/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARXR346UT5/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXT196WPG/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARXT727MD7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXU376FDN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXV209WYA/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARXX895FNJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARXY240WJC/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARXY532ZTT/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARXZ902NFM/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYA030ZG7/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYA379LKT/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYA556KP8/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYA955CY1/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYC243UW5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYC287UFV/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYC466ER1/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYD195BDH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYD585PXP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYE221LZB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYE850ZVD/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYF699FW0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYG665JUD/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYG874EKA/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYG988PUQ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYH603BDN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYH697TPA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYJ334EHH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYK042VMG/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYK164AEJ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYL758JGG/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYM063XB8/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYM334BZ5/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYM586MYN/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYN152YMW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYN174NPH/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYR829KD8/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYU120NDA/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYU345GZJ/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYW170CAA/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARYW789GNP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYW945PJU/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYW984FLT/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYX008UCU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYX133FFQ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARYX853TAX/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARYY419ZXX/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARYY664KHF/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZA982YTP/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARZB517KTU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZE963MEU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZF170TZ0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZG236AUT/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZG690NHH/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZH521MMD/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZH672BAM/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZJ539CD9/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZJ587UZU/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZJ603JM0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZK732FZ0/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZK745JGG/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZL113CU0/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZL799MFW/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZL855WVA/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZM580BG2/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZM903TNL/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZN277NR6/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZN610GTY/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZN914GPB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZP599GRG/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZP630WYL/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZR180BM6/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZT581RNV/ses-HBNsiteCUNY/anat/*_T*w.*
datalad get sub-NDARZT957CWG/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZU279XR3/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZV421TCZ/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZV749GAP/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZW363UGM/ses-HBNsiteRU/anat/*_T*w.*
datalad get sub-NDARZW873DN3/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZX163EWC/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZY101JNB/ses-HBNsiteCBIC/anat/*_T*w.*
datalad get sub-NDARZY668NMV/ses-HBNsiteRU/anat/*_T*w.*
